import test from "node:test";
import assert from "node:assert/strict";
import { InMemoryAssetStore } from "../src/assets/in-memory-asset-store.js";
import { InMemoryOperationsStore } from "../src/operations/in-memory-operations-store.js";
import { OperationsService } from "../src/operations/operations-service.js";

const actor={userId:"10000000-0000-4000-8000-000000000001",organizationId:"20000000-0000-4000-8000-000000000001",sessionId:"30000000-0000-4000-8000-000000000001",role:"owner"};
const setup=async()=>{const store=new InMemoryOperationsStore(),assetStore=new InMemoryAssetStore();const service=new OperationsService({store,assetStore,clock:()=>new Date("2026-08-07T12:00:00Z")});await assetStore.createAsset({id:"40000000-0000-4000-8000-000000000001",organizationId:actor.organizationId,createdByUserId:actor.userId,name:"Interview",originalFilename:"a.mp4",storageKey:"key",mimeType:"video/mp4",sizeBytes:100});return{store,service};};

test("billing subscriptions expose plan entitlements and usage is idempotent",async()=>{const{store,service}=await setup();const subscription=await service.setSubscription({actor,planCode:"studio",status:"active"});assert.equal(subscription.planCode,"studio");assert.equal((await service.getSubscription({actor})).entitlements.members,15);const first=await service.recordUsage({actor,metric:"ai.minutes",quantity:12,idempotencyKey:"usage:event:1234"});const replay=await service.recordUsage({actor,metric:"ai.minutes",quantity:12,idempotencyKey:"usage:event:1234"});assert.equal(first.id,replay.id);assert.equal(store.usage.size,1);});
test("notifications are user scoped and read idempotently",async()=>{const{service}=await setup();const item=await service.notify({actor,kind:"render.ready",title:"Render ready",body:"Your export is ready."});assert.equal((await service.notifications({actor})).length,1);assert.ok((await service.readNotification({actor,notificationId:item.id})).readAt);});
test("translation and rendering jobs validate assets and idempotency",async()=>{const{store,service}=await setup();const translation=await service.requestTranslation({actor,assetId:"40000000-0000-4000-8000-000000000001",sourceLanguage:"en",targetLanguage:"fr",idempotencyKey:"translation:1234"});const replay=await service.requestTranslation({actor,assetId:"40000000-0000-4000-8000-000000000001",sourceLanguage:"en",targetLanguage:"fr",idempotencyKey:"translation:1234"});assert.equal(translation.id,replay.id);const render=await service.requestRender({actor,assetId:"40000000-0000-4000-8000-000000000001",format:"mp4",width:1920,height:1080,idempotencyKey:"render:12345678"});assert.equal(render.jobType,"render");assert.equal((await service.cancelJob({actor,jobId:render.id})).status,"canceled");assert.equal(store.jobs.size,2);});
test("admins can inspect jobs but cannot change billing",async()=>{const{service}=await setup();const admin={...actor,role:"admin"};assert.deepEqual((await service.adminOverview({actor:admin})).jobs,[]);await assert.rejects(()=>service.setSubscription({actor:admin,planCode:"studio"}),error=>error.code==="AUTH_FORBIDDEN");});
test("notification preferences control delivery channels",async()=>{const{store,service}=await setup();await service.setNotificationPreference({actor,channel:"email",destination:"owner@example.test",enabled:true});assert.equal((await service.notificationPreferences({actor}))[0].channel,"email");const item=await service.notify({actor,kind:"render.ready",title:"Ready",body:"Export ready"});assert.equal(store.deliveries.get(`delivery-${item.id}-email`).destination,"owner@example.test");});
test("operators inspect timelines, retry dead letters, and record reconciliation",async()=>{const{store,service}=await setup();const job=await service.requestRender({actor,assetId:"40000000-0000-4000-8000-000000000001",format:"mp4",width:1280,height:720,idempotencyKey:"render:governance"});job.status="dead_letter";job.attempts=5;assert.equal((await service.retryJob({actor,jobId:job.id})).status,"queued");assert.equal((await service.job({actor,jobId:job.id})).events[0].eventType,"operator_retry");const record=await service.reconcileProvider({actor,provider:"renderco",resourceType:"render",externalId:"ext-1",status:"drifted",expected:{state:"ready"},observed:{state:"missing"}});assert.equal(record.status,"drifted");assert.equal(store.reconciliations.length,1);});
