import test from "node:test";
import assert from "node:assert/strict";
import { createHmac } from "node:crypto";
import { BillingWebhookService } from "../src/operations/billing-webhook-service.js";
import { InMemoryOperationsStore } from "../src/operations/in-memory-operations-store.js";
import { OperationWorker } from "../src/operations/operation-worker.js";
import { NotificationWorker } from "../src/operations/notification-worker.js";

const now=new Date("2026-08-08T12:00:00Z");
test("billing webhooks verify signatures and process events once",async()=>{const store=new InMemoryOperationsStore(),secret="test-billing-webhook-secret-at-least-32-characters";const service=new BillingWebhookService({store,secret,clock:()=>now});const raw=JSON.stringify({id:"evt_1",type:"subscription.updated",provider:"test",data:{organizationId:"org-1",planCode:"studio",status:"active",subscriptionId:"sub_1"}});const timestamp=Math.floor(now.getTime()/1000);const digest=createHmac("sha256",secret).update(`${timestamp}.${raw}`).digest("hex");assert.deepEqual(await service.handle({rawBody:raw,signature:`t=${timestamp},v1=${digest}`}),{duplicate:false});assert.deepEqual(await service.handle({rawBody:raw,signature:`t=${timestamp},v1=${digest}`}),{duplicate:true});assert.equal((await store.getSubscription("org-1")).planCode,"studio");});
test("operation worker completes provider output and retries failures",async()=>{const store=new InMemoryOperationsStore();await store.createJob({id:"job-1",organizationId:"org",jobType:"translation",assetId:"asset",input:{},idempotencyKey:"key",status:"queued",attempts:0,createdAt:now,updatedAt:now});const worker=new OperationWorker({store,translationProvider:{execute:async()=>({text:"Bonjour"})},renderProvider:{execute:async()=>({})},workerId:"worker",clock:()=>now});assert.equal(await worker.processNext(),true);assert.equal((await store.getJob("org","job-1")).status,"completed");});
test("notification worker delivers queued outbox entries",async()=>{const store=new InMemoryOperationsStore();await store.createNotification({id:"note-1",organizationId:"org",userId:"user",kind:"test",title:"Ready",body:"Done",metadata:{},createdAt:now});const worker=new NotificationWorker({store,provider:{send:async()=>({messageId:"msg-1"})},workerId:"worker",clock:()=>now});assert.equal(await worker.processNext(),true);assert.equal(store.deliveries.get("delivery-note-1").status,"delivered");});
