import React, { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { normalizeRoute } from "./routes.js";
import "./styles.css";

const media = [
  { id: 1, name: "Campaign interview — Maya", type: "Video", meta: "8:42", insight: "6 AI insights", tone: "violet" },
  { id: 2, name: "Future of work podcast", type: "Audio", meta: "24:19", insight: "Transcript ready", tone: "coral" },
  { id: 3, name: "London editorial selects", type: "Images", meta: "24 files", insight: "18 tags", tone: "mint" },
  { id: 4, name: "Product launch keynote", type: "Video", meta: "31:05", insight: "12 chapters", tone: "blue" },
  { id: 5, name: "Social campaign stills", type: "Images", meta: "48 files", insight: "9 people", tone: "mint" },
  { id: 6, name: "Customer research — round 3", type: "Audio", meta: "42:08", insight: "14 themes", tone: "coral" }
];

function Icon({ name }) { return <span className="icon" aria-hidden="true">{({ play: "▶", search: "⌕", upload: "↑", grid: "▦", library: "▧", spark: "✦", folder: "▱", users: "♙", settings: "⚙", bell: "◦", back: "←" })[name] || "·"}</span>; }
function Button({ children, primary = false, quiet = false, onClick, type = "button" }) { return <button type={type} className={`button ${primary ? "primary" : ""} ${quiet ? "quiet" : ""}`} onClick={onClick}>{children}</button>; }
function Logo() { return <a className="logo" href="/" data-link><span className="logo-mark">T</span><span>TudiMedia</span></a>; }
function MarketingHeader({ navigate }) { return <header className="marketing-header"><Logo/><nav aria-label="Main navigation"><a href="/#platform">Platform</a><a href="/#solutions">Solutions</a><a href="/pricing" data-link>Pricing</a><a href="/#resources">Resources</a></nav><div className="header-actions"><Button quiet onClick={() => navigate("/app")}>Sign in</Button><Button primary onClick={() => navigate("/app")}>Start creating</Button></div></header>; }

function Landing({ navigate }) { return <div className="marketing"><MarketingHeader navigate={navigate}/><main><section className="hero"><div className="hero-copy"><span className="eyebrow">AI media intelligence</span><h1>Every story, instantly within reach.</h1><p>Upload, understand, edit, and activate your entire media library from one intelligent workspace.</p><div className="hero-actions"><Button primary onClick={() => navigate("/app")}>Start free</Button><Button>Watch overview</Button></div><div className="hero-proof"><strong>Built for serious media</strong><span>Private by default</span><span>Source-linked AI</span><span>Enterprise controls</span></div></div><div className="hero-media"><div className="video-label"><span>AI highlight detected</span><span>01:24 / 08:42</span></div><blockquote>“The moment we changed our approach, <em>engagement doubled.</em>”</blockquote><div>Campaign interview · Maya Chen</div></div></section><section className="feature-band" id="platform"><span className="eyebrow">One connected workflow</span><h2>From raw footage to remarkable work.</h2><div className="feature-grid"><article><b>01</b><h3>Ingest safely</h3><p>Direct uploads, malware scanning, metadata extraction, and dependable processing.</p></article><article><b>02</b><h3>Understand everything</h3><p>Transcripts, summaries, chapters, people, objects, moderation, and provenance.</p></article><article><b>03</b><h3>Create with confidence</h3><p>Find exact moments, build cuts, review work, and export with the source always attached.</p></article></div></section></main><Footer/></div>; }

function Pricing({ navigate }) { const plans=[{name:"Creator",price:"£19",items:["500 GB storage","20 AI hours","3 members"]},{name:"Studio",price:"£79",featured:true,items:["3 TB storage","150 AI hours","15 members","Advanced review"]},{name:"Enterprise",price:"Custom",items:["Flexible storage","SSO and SCIM","Regional controls","Priority support"]}]; return <div className="marketing"><MarketingHeader navigate={navigate}/><main className="pricing"><span className="eyebrow">Simple, scalable pricing</span><h1>Start creating. Scale without limits.</h1><p>Secure storage, AI enrichment, and collaboration are included in every plan.</p><div className="plan-grid">{plans.map(plan=><article className={`plan ${plan.featured?"featured":""}`} key={plan.name}>{plan.featured&&<span className="plan-label">Most popular</span>}<h2>{plan.name}</h2><div className="price">{plan.price}{plan.price!=="Custom"&&<small>/month</small>}</div><Button primary={plan.featured} onClick={()=>navigate("/app")}>{plan.name==="Enterprise"?"Contact sales":"Start free"}</Button><ul>{plan.items.map(item=><li key={item}>{item}</li>)}</ul></article>)}</div></main><Footer/></div>; }

function AppShell({ route, navigate, children }) { const links=[["/app","grid","Overview"],["/app/library","library","Library"],["/app/editor","spark","Media editor"],["/app/admin","users","Admin"],["/app/design-system","settings","Design system"]]; return <div className="app-shell"><aside className="sidebar"><Logo/><div className="workspace-picker"><span className="avatar">TM</span><span><b>Tudi Media Studio</b><small>Production workspace</small></span></div><nav aria-label="Workspace navigation">{links.map(([path,icon,label])=><a href={path} data-link className={route===path?"active":""} key={path}><Icon name={icon}/><span>{label}</span></a>)}</nav><div className="sidebar-account"><span className="avatar">MC</span><span><b>Maya Chen</b><small>Owner</small></span></div></aside><div className="app-main"><header className="app-header"><label className="global-search"><Icon name="search"/><span className="sr-only">Search</span><input placeholder="Search moments, people, dialogue…"/></label><Button quiet><Icon name="bell"/> Activity</Button><Button primary><Icon name="upload"/> Upload</Button></header>{children}<nav className="mobile-nav">{links.slice(0,4).map(([path,icon,label])=><a href={path} data-link className={route===path?"active":""} key={path}><Icon name={icon}/><span>{label}</span></a>)}</nav></div></div>; }
function PageHeading({ eyebrow, title, copy, action }) { return <div className="page-heading"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h1>{title}</h1><p>{copy}</p></div>{action}</div>; }
function MediaCard({ item, open }) { return <article className="media-card" onClick={open}><div className={`media-thumb ${item.tone}`}><span className="ready">AI ready</span><span className="play"><Icon name="play"/></span><span className="duration">{item.meta}</span></div><div className="media-copy"><h3>{item.name}</h3><div><span>{item.type}</span><span className="insight">{item.insight}</span></div></div></article>; }
function Dashboard({ navigate }) { return <main className="app-page"><PageHeading title="Good morning, Maya" copy="Here’s what’s moving in your workspace." action={<Button primary><Icon name="upload"/> Upload media</Button>}/><section className="stats"><article><small>Media assets</small><strong>12,842</strong><span>+328 this month</span></article><article><small>Hours processed</small><strong>1,904</strong><span>97% AI ready</span></article><article><small>Storage</small><strong>8.4 TB</strong><span>of 12 TB</span></article></section><div className="section-heading"><h2>Continue working</h2><a href="/app/library" data-link>View library →</a></div><section className="media-grid">{media.slice(0,3).map(item=><MediaCard item={item} open={()=>navigate("/app/editor")} key={item.id}/>)}</section></main>; }
function Library({ navigate }) { const [filter,setFilter]=useState("All"); const [query,setQuery]=useState(""); const shown=media.filter(x=>(filter==="All"||x.type===filter)&&x.name.toLowerCase().includes(query.toLowerCase())); return <main className="app-page"><PageHeading title="Media library" copy="Everything your team has uploaded, processed, and enriched."/><div className="library-tools"><label><span className="sr-only">Filter library</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Filter this library…"/></label><div className="chips">{["All","Video","Audio","Images"].map(x=><button aria-pressed={filter===x} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div></div><section className="media-grid">{shown.map(item=><MediaCard item={item} open={()=>navigate("/app/editor")} key={item.id}/>)}</section></main>; }
function Editor() { return <main className="editor"><section className="editor-stage"><div className="editor-top"><Button quiet><Icon name="back"/> Library</Button><span>Auto-saved</span></div><div className="canvas"><span className="caption">The moment we changed our approach…</span></div><div className="timeline"><small>VIDEO 1</small><div className="track"><span/></div><small>CAPTIONS</small><div className="track captions"><span/></div></div></section><aside className="inspector"><span className="eyebrow">AI tools</span><h2>Find the story faster.</h2><p>Transform media with source-linked intelligence.</p><label>Find a moment<input defaultValue="customer engagement"/></label><Button primary>Find highlights</Button><label>Caption style<select defaultValue="clean"><option value="clean">Clean editorial</option><option value="bold">Bold social</option></select></label><article className="suggestion"><b>Suggested cut</b><span>42 seconds · High confidence</span><Button>Preview cut</Button></article></aside></main>; }
function Admin() { const rows=[["API Gateway","London","Healthy","118 ms"],["Media workers","London","Healthy","42s queue"],["AI enrichment","EU multi-region","Healthy","3.8 min"],["Search","London","Healthy","204 ms"]]; return <main className="app-page"><PageHeading eyebrow="Administration" title="Platform operations" copy="Live service, tenant, and governance health." action={<Button>View audit log</Button>}/><section className="stats"><article><small>API availability</small><strong>99.98%</strong><span>30-day window</span></article><article><small>Queue age</small><strong>42s</strong><span>Within SLO</span></article><article><small>AI spend today</small><strong>£4,820</strong><span>68% of budget</span></article></section><div className="table-wrap"><table><thead><tr><th>Service</th><th>Region</th><th>Status</th><th>p95</th></tr></thead><tbody>{rows.map(row=><tr key={row[0]}>{row.map((cell,i)=><td className={i===2?"status":""} key={cell}>{cell}</td>)}</tr>)}</tbody></table></div></main>; }
function DesignSystem() { return <main className="app-page"><PageHeading eyebrow="TudiMedia design system" title="Clear, expressive, built for focus." copy="Accessible foundations for dense media workflows and calm creative decision-making."/><h2>Core palette</h2><div className="swatches"><div className="swatch signal">Signal violet<span>#6541D8</span></div><div className="swatch highlight">Highlight lime<span>#D9FF66</span></div><div className="swatch ink">Ink<span>#15121D</span></div><div className="swatch canvas-swatch">Canvas<span>#F5F3FA</span></div><div className="swatch critical">Critical<span>#E45B68</span></div></div><h2>Components</h2><div className="component-row"><Button primary>Primary action</Button><Button>Secondary action</Button><span className="ready static">AI ready</span><label className="demo-input">Field<input placeholder="Search media…"/></label></div><section className="brand-panel"><div><span className="eyebrow">Brand promise</span><h2>Media, made meaningful.</h2><p>Every valuable moment, instantly within reach.</p></div><div><h3>Interaction principles</h3><p>Show progress. Preserve context. Keep AI explainable. Make destructive actions unmistakable. Never hide tenant or permission boundaries.</p></div></section></main>; }
function NotFound({ navigate }) { return <main className="not-found"><Logo/><h1>That page is out of frame.</h1><p>The resource may have moved or you may not have permission to view it.</p><Button primary onClick={()=>navigate("/")}>Return home</Button></main>; }
function Footer(){return <footer><Logo/><span>© 2026 TudiMedia</span><span>Security · Privacy · Status</span></footer>}
function App(){ const [route,setRoute]=useState(normalizeRoute(location.pathname)); const navigate=(path)=>{history.pushState({},"",path);setRoute(normalizeRoute(path));scrollTo({top:0,behavior:"smooth"})}; useEffect(()=>{const pop=()=>setRoute(normalizeRoute(location.pathname));const click=e=>{const link=e.target.closest("[data-link]");if(link&&link.origin===location.origin){e.preventDefault();navigate(link.pathname)}};addEventListener("popstate",pop);document.addEventListener("click",click);return()=>{removeEventListener("popstate",pop);document.removeEventListener("click",click)}},[]); if(route==="/")return <Landing navigate={navigate}/>;if(route==="/pricing")return <Pricing navigate={navigate}/>;if(route==="/not-found")return <NotFound navigate={navigate}/>;let page=route==="/app"?<Dashboard navigate={navigate}/>:route==="/app/library"?<Library navigate={navigate}/>:route==="/app/editor"?<Editor/>:route==="/app/admin"?<Admin/>:<DesignSystem/>;return <AppShell route={route} navigate={navigate}>{page}</AppShell> }
createRoot(document.getElementById("root")).render(<React.StrictMode><App/></React.StrictMode>);
