import { randomUUID } from "node:crypto";
import { AuthError } from "../auth/errors.js";
import { requirePermission } from "../auth/roles.js";

const plans = Object.freeze({ creator: { storageBytes: 500_000_000_000, aiMinutes: 1200, members: 3 }, studio: { storageBytes: 3_000_000_000_000, aiMinutes: 9000, members: 15 }, enterprise: { storageBytes: null, aiMinutes: null, members: null } });
const language = (value) => /^[a-z]{2,3}(?:-[A-Z]{2})?$/.test(String(value ?? ""));
const key = (value) => { const result=String(value??"").trim(); if(!/^[A-Za-z0-9._:-]{8,128}$/.test(result)) throw new AuthError("IDEMPOTENCY_KEY_INVALID","A valid idempotency key is required.",422); return result; };

export class OperationsService {
  constructor({ store, assetStore, clock=()=>new Date() }) { this.store=store;this.assetStore=assetStore;this.clock=clock; }
  async getSubscription({ actor }) { requirePermission(actor.role,"assets:read"); const subscription=await this.store.getSubscription(actor.organizationId); return subscription ? { ...subscription, entitlements: plans[subscription.planCode] } : { planCode:"creator",status:"trialing",entitlements:plans.creator }; }
  async setSubscription({ actor, planCode, status="active", provider=null, providerCustomerId=null, providerSubscriptionId=null, currentPeriodEnd=null }) { requirePermission(actor.role,"billing:manage"); if(!plans[planCode]||!["trialing","active","past_due","canceled"].includes(status)) throw new AuthError("BILLING_VALIDATION","Plan or subscription status is invalid.",422); const subscription=await this.store.upsertSubscription({organizationId:actor.organizationId,planCode,status,provider,providerCustomerId,providerSubscriptionId,currentPeriodEnd:currentPeriodEnd?new Date(currentPeriodEnd):null}); await this.audit(actor,"billing.subscription_updated",{planCode,status}); return subscription; }
  async recordUsage({ actor, metric, quantity, idempotencyKey, metadata={} }) { requirePermission(actor.role,"operations:manage"); const numeric=Number(quantity); if(!/^[a-z][a-z0-9_.]{2,63}$/.test(String(metric))||!Number.isSafeInteger(numeric)||numeric<1) throw new AuthError("USAGE_VALIDATION","Usage metric or quantity is invalid.",422); return this.store.recordUsage({id:randomUUID(),organizationId:actor.organizationId,metric,quantity:numeric,idempotencyKey:key(idempotencyKey),occurredAt:this.clock(),metadata}); }
  async notify({ actor, kind, title, body, metadata={} }) { requirePermission(actor.role,"operations:manage"); if(!/^[a-z][a-z0-9_.-]{2,63}$/.test(String(kind))||!String(title).trim()||String(title).length>160||!String(body).trim()||String(body).length>2000) throw new AuthError("NOTIFICATION_VALIDATION","Notification content is invalid.",422); const notification=await this.store.createNotification({id:randomUUID(),organizationId:actor.organizationId,userId:actor.userId,kind,title:String(title).trim(),body:String(body).trim(),metadata,readAt:null,createdAt:this.clock()}); await this.audit(actor,"notification.created",{notificationId:notification.id,kind}); return notification; }
  async notifications({ actor }) { return this.store.listNotifications(actor.organizationId,actor.userId); }
  async readNotification({ actor, notificationId }) { const item=await this.store.markNotificationRead(actor.organizationId,actor.userId,notificationId,this.clock()); if(!item) throw new AuthError("NOTIFICATION_NOT_FOUND","Notification not found.",404); return item; }
  async requestTranslation({ actor, assetId, sourceLanguage, targetLanguage, idempotencyKey }) { requirePermission(actor.role,"assets:write"); if(!language(sourceLanguage)||!language(targetLanguage)||sourceLanguage===targetLanguage) throw new AuthError("TRANSLATION_VALIDATION","Source and target languages must be valid and different.",422); return this.createAssetJob({actor,assetId,jobType:"translation",input:{sourceLanguage,targetLanguage},idempotencyKey}); }
  async requestRender({ actor, assetId, format, width, height, idempotencyKey }) { requirePermission(actor.role,"assets:write"); const w=Number(width),h=Number(height); if(!["mp4","webm"].includes(format)||!Number.isInteger(w)||!Number.isInteger(h)||w<240||h<240||w>7680||h>4320) throw new AuthError("RENDER_VALIDATION","Render format or dimensions are invalid.",422); return this.createAssetJob({actor,assetId,jobType:"render",input:{format,width:w,height:h},idempotencyKey}); }
  async createAssetJob({actor,assetId,jobType,input,idempotencyKey}) { const asset=await this.assetStore.getAsset(actor.organizationId,assetId); if(!asset) throw new AuthError("ASSET_NOT_FOUND","Asset not found.",404); const job=await this.store.createJob({id:randomUUID(),organizationId:actor.organizationId,requestedByUserId:actor.userId,assetId,jobType,input,idempotencyKey:key(idempotencyKey),status:"queued",attempts:0,createdAt:this.clock(),updatedAt:this.clock()}); await this.audit(actor,`operation.${jobType}_queued`,{jobId:job.id,assetId}); return job; }
  async adminOverview({ actor }) { requirePermission(actor.role,"operations:read"); return { subscription:await this.getSubscription({actor}),jobs:await this.store.listJobs(actor.organizationId,100) }; }
  async cancelJob({ actor, jobId }) { requirePermission(actor.role,"operations:manage"); const job=await this.store.cancelJob(actor.organizationId,jobId,this.clock()); if(!job) throw new AuthError("OPERATION_JOB_NOT_CANCELABLE","Job not found or cannot be canceled.",409); return job; }
  async audit(actor,action,metadata) { await this.assetStore.appendAudit({organizationId:actor.organizationId,actorUserId:actor.userId,sessionId:actor.sessionId,action,metadata}); }
}
